# Generated by Django 4.0 on 2023-08-04 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_city_active', models.BooleanField(default=True)),
                ('city_name', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('is_provience_center', models.BooleanField(default=False)),
                ('city_createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Countrymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_country_active', models.BooleanField(default=True)),
                ('country_name', models.CharField(blank=True, default='iran', max_length=200, null=True, verbose_name='Country')),
                ('country_code', models.CharField(max_length=10, null=True, verbose_name='Code')),
                ('country_center', models.CharField(max_length=200, null=True, verbose_name='Country Center')),
                ('country_iso_code_short', models.CharField(max_length=2, null=True, verbose_name='ISO Code Short')),
                ('country_iso_code_long', models.CharField(max_length=3, null=True, verbose_name='ISO Code Long')),
                ('country_numeric_code', models.CharField(max_length=3, null=True, verbose_name='Numeric Code')),
                ('allowsbilling', models.BooleanField(default=True)),
                ('allowsshipping', models.BooleanField(default=True)),
                ('displayorder', models.IntegerField(max_length=10, null=True)),
                ('numberofproviences', models.IntegerField(max_length=10, null=True)),
                ('country_createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Proviencemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_provience_active', models.BooleanField(default=True)),
                ('provience_name', models.CharField(max_length=200, null=True, verbose_name='Provience')),
                ('provience_center', models.CharField(max_length=10, null=True, verbose_name='provience_center')),
                ('provience_center_code', models.CharField(max_length=10, null=True, verbose_name='Provience Code')),
                ('is_country_center', models.BooleanField(default=False)),
                ('provience_createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
