# Generated by Django 4.0 on 2023-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='iran', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='provience',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country', unique=True),
        ),
    ]
