# Generated by Django 4.0 on 2023-08-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Proviences',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='country_create_date',
        ),
    ]
