# Generated by Django 4.0 on 2023-08-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cities_proviences'),
    ]

    operations = [
        migrations.AddField(
            model_name='proviences',
            name='countries',
            field=models.ForeignKey(default='Country name', on_delete=django.db.models.deletion.CASCADE, to='common.countries'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(default='Country Name', max_length=200),
        ),
    ]
