# Generated by Django 4.0 on 2023-08-03 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country_country_code_country_iso_code_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso_code_long',
            new_name='country_iso_code_long',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='iso_code_short',
            new_name='country_iso_code_short',
        ),
        migrations.AddField(
            model_name='country',
            name='country_createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
