# Generated by Django 4.0 on 2023-08-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_countries_country_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proviences',
            name='countries',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='common.countries'),
        ),
    ]
