# Generated by Django 4.0 on 2023-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_city_city_createdate_city_is_city_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provience',
            name='provience_center',
            field=models.CharField(max_length=10, null=True, verbose_name='provience_center'),
        ),
    ]
