# Generated by Django 4.0 on 2023-08-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_proviences_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proviences',
            name='countries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.countries'),
        ),
    ]
