# Generated by Django 4.0 on 2023-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='displayorder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='storevat',
            field=models.IntegerField(),
        ),
    ]
